language: node_js
node_js:
  - "12"
  
services:
  - docker

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t wtc/node-pm2:latest .
  - docker push wtc/node-pm2:latest