language: node_js

node_js:
  - "12"

branches:
  only:
  - master

services:
  - docker

before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  - docker build -t tcly861204/node:latest .

after_script:
  - docker push tcly861204/node:latest